sudo: required
before_install:
  - sudo apt-get install pgxnclient postgresql-server-dev-all
  - sudo pgxn install temporal_tables
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install: pip install tox-travis
script: tox
addons:
  postgresql: "9.2"
services:
  - postgresql
